// Autogenerated from Pigeon (v6.0.3), do not edit directly.
// See also: https://pub.dev/packages/pigeon

#import <Foundation/Foundation.h>

@protocol FlutterBinaryMessenger;
@protocol FlutterMessageCodec;
@class FlutterError;
@class FlutterStandardTypedData;

NS_ASSUME_NONNULL_BEGIN

@class PigeonUserDetails;

@interface PigeonUserDetails : NSObject
/// `init` unavailable to enforce nonnull fields, see the `make` class method.
- (instancetype)init NS_UNAVAILABLE;
+ (instancetype)makeWithUserId:(NSString *)userId
    phoneNumber:(NSString *)phoneNumber;
@property(nonatomic, copy) NSString * userId;
@property(nonatomic, copy) NSString * phoneNumber;
@end

/// The codec used by UserApi.
NSObject<FlutterMessageCodec> *UserApiGetCodec(void);

@protocol UserApi
/// @return `nil` only when `error != nil`.
- (nullable PigeonUserDetails *)getUserDetailsWithError:(FlutterError *_Nullable *_Nonnull)error;
@end

extern void UserApiSetup(id<FlutterBinaryMessenger> binaryMessenger, NSObject<UserApi> *_Nullable api);

NS_ASSUME_NONNULL_END
