// Autogenerated from Pigeon (v6.0.3), do not edit directly.
// See also: https://pub.dev/packages/pigeon

#import "Pigeon.h"
#import <Flutter/Flutter.h>

#if !__has_feature(objc_arc)
#error File requires ARC to be enabled.
#endif

static NSArray *wrapResult(id result, FlutterError *error) {
  if (error) {
    return @[ error.code ?: [NSNull null], error.message ?: [NSNull null], error.details ?: [NSNull null] ];
  }
  return @[ result ?: [NSNull null]  ];
}
static id GetNullableObject(NSDictionary* dict, id key) {
  id result = dict[key];
  return (result == [NSNull null]) ? nil : result;
}
static id GetNullableObjectAtIndex(NSArray* array, NSInteger key) {
  id result = array[key];
  return (result == [NSNull null]) ? nil : result;
}


@interface PigeonUserDetails ()
+ (PigeonUserDetails *)fromList:(NSArray *)list;
+ (nullable PigeonUserDetails *)nullableFromList:(NSArray *)list;
- (NSArray *)toList;
@end


@implementation PigeonUserDetails
+ (instancetype)makeWithUserId:(NSString *)userId
    phoneNumber:(NSString *)phoneNumber {
  PigeonUserDetails* pigeonResult = [[PigeonUserDetails alloc] init];
  pigeonResult.userId = userId;
  pigeonResult.phoneNumber = phoneNumber;
  return pigeonResult;
}
+ (PigeonUserDetails *)fromList:(NSArray *)list {
  PigeonUserDetails *pigeonResult = [[PigeonUserDetails alloc] init];
  pigeonResult.userId = GetNullableObjectAtIndex(list, 0);
  NSAssert(pigeonResult.userId != nil, @"");
  pigeonResult.phoneNumber = GetNullableObjectAtIndex(list, 1);
  NSAssert(pigeonResult.phoneNumber != nil, @"");
  return pigeonResult;
}
+ (nullable PigeonUserDetails *)nullableFromList:(NSArray *)list { return (list) ? [PigeonUserDetails fromList:list] : nil; }
- (NSArray *)toList {
  return @[
    (self.userId ?: [NSNull null]),
    (self.phoneNumber ?: [NSNull null]),
  ];
}
@end

@interface UserApiCodecReader : FlutterStandardReader
@end
@implementation UserApiCodecReader
- (nullable id)readValueOfType:(UInt8)type 
{
  switch (type) {
    case 128:     
      return [PigeonUserDetails fromList:[self readValue]];
    
    default:    
      return [super readValueOfType:type];
    
  }
}
@end

@interface UserApiCodecWriter : FlutterStandardWriter
@end
@implementation UserApiCodecWriter
- (void)writeValue:(id)value 
{
  if ([value isKindOfClass:[PigeonUserDetails class]]) {
    [self writeByte:128];
    [self writeValue:[value toList]];
  } else 
{
    [super writeValue:value];
  }
}
@end

@interface UserApiCodecReaderWriter : FlutterStandardReaderWriter
@end
@implementation UserApiCodecReaderWriter
- (FlutterStandardWriter *)writerWithData:(NSMutableData *)data {
  return [[UserApiCodecWriter alloc] initWithData:data];
}
- (FlutterStandardReader *)readerWithData:(NSData *)data {
  return [[UserApiCodecReader alloc] initWithData:data];
}
@end


NSObject<FlutterMessageCodec> *UserApiGetCodec() {
  static FlutterStandardMessageCodec *sSharedObject = nil;
  static dispatch_once_t sPred = 0;
  dispatch_once(&sPred, ^{
    UserApiCodecReaderWriter *readerWriter = [[UserApiCodecReaderWriter alloc] init];
    sSharedObject = [FlutterStandardMessageCodec codecWithReaderWriter:readerWriter];
  });
  return sSharedObject;
}

void UserApiSetup(id<FlutterBinaryMessenger> binaryMessenger, NSObject<UserApi> *api) {
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:@"dev.flutter.pigeon.UserApi.getUserDetails"
        binaryMessenger:binaryMessenger
        codec:UserApiGetCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(getUserDetailsWithError:)], @"UserApi api (%@) doesn't respond to @selector(getUserDetailsWithError:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        FlutterError *error;
        PigeonUserDetails *output = [api getUserDetailsWithError:&error];
        callback(wrapResult(output, error));
      }];
    }
    else {
      [channel setMessageHandler:nil];
    }
  }
}
